version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
    ports:
      - "3306:3306"

  customers-api:
    build: ./customers-api
    env_file:
      - ./customers-api/.env
    depends_on:
      - mysql
    ports:
      - "3001:3001"
    volumes:
      - ./customers-api:/usr/src/app
    command: ["npm","run","dev"]

  orders-api:
    build: ./orders-api
    env_file:
      - ./orders-api/.env
    depends_on:
      - mysql
      - customers-api
    ports:
      - "3002:3002"
    volumes:
      - ./orders-api:/usr/src/app
    command: ["npm","run","dev"]

volumes:
  db_data: